//@version=1
//Heikin Ashi Strategy V1 by agbarbosa
//Simple crossover EMA + SMA with Heikin Ashi data

strategy("Heikin Ashi Strategy - by agbarbosa",shorttitle="HAS V1",overlay=true,default_qty_value=100,initial_capital=400,currency=currency.AUD)

hshift = input(1,title="Heikin Ashi Candle Time Frame Shift")
mhshift = input(0,title="Heikin Ashi EMA Time Frame Shift")
fama = input(1,"Heikin Ashi EMA Period")
test = input(0,"Heikin Ashi EMA Shift")
sloma = input(30,"Slow EMA Period")
slomas = input(0,"Slow EMA Shift")

//Heikin Ashi Open/Close Price
ha_t = heikinashi(tickerid)
ha_open = security(ha_t, 15, open[hshift])
ha_close = security(ha_t, 15, close[hshift])
mha_close = security(ha_t, 240, close[mhshift])

//Moving Average
fma = ema(mha_close[test],fama)
sma = ema(ha_close[slomas],sloma)
plot(fma,title="MA",color=lime,linewidth=2,style=line)
plot(sma,title="SMA",color=red,linewidth=2,style=line)

//Strategy
golong =  crossover(fma,sma) 
goshort =   crossunder(fma,sma)

strategy.entry("Buy",strategy.long, when = golong)
strategy.entry("Sell",strategy.short,when = goshort)

